import type { Metadata } from 'next';
import { Geist, Geist_Mono, Poppins } from 'next/font/google';
import './globals.css';
import { Header } from '../common/layout/header/Header';
import Footer from '../common/layout/footer/Footer';
import { auth } from '@base/auth';
import { SessionProvider } from 'next-auth/react';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});
const poppins = Poppins({
	subsets: ['latin'],
	variable: '--font-poppins',
	weight: ['400', '500', '600', '700', '800'], // o los pesos que vayas a usar
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<SessionProvider session={session}>
			<html lang="es" suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${poppins.className} ${geistMono.variable}  antialiased `}
				>
					<Header />
					{children}
					<Footer />
				</body>
			</html>
		</SessionProvider>
	);
}
